### ISSUE TITLE
Specify or detect cloud infra for existing-ocp

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#114]
Some OpenShift actions in the deployer depend on the infrastructure that is being deployed on. Examples:
- NetworkPolicy is needed for ROKS for Watson Discovery: #111 
- Machine Config Operator does not exist for ROKS
- ImageContentSourcePolicy cannot be created for ROSA
- MCP labels are not allowed for ROSA

These limitations sometimes lead to unexpected errors in the deployment process which should be caught. Allow specifying the cloud infrastructure for existing-ocp `openshift` definitions and/or detect it automatically.

**Comment by yefei0423** [comment]
@fketelaars , we could add condition control for different cloud infrastructure.  For the first item task #111 , it is done.  But for the others,  is there sub-task for more detailed information? 
```
Machine Config Operator does not exist for ROKS   --->   IBM Cloud 
ImageContentSourcePolicy cannot be created for ROSA    ---> AWS ROSA
MCP labels are not allowed for ROSA   ---> AWS ROSA
```

**Comment by fketelaars** [comment]
@yefei0423 can you please make the following changes to the `openshift` definition for `existing-ocp`:
```
openshift:
- name: "{{ env_id }}"
  ocp_version: 4.8
  cluster_name: "{{ env_id }}"
  domain_name: example.com
  infrastructure:
    type: roks
```

The values for `infrastructure.type` can be:
- ibm-roks
- aws-self-managed
- aws-rosa
- azure-aro
- vsphere
- standard - this value means no special handling takes place
- detect - this value will cause the deployer to detect the infrastructure type

In the case of handling `existing-ocp`, set the Ansible fact _existing_ocp_infra_type to the appropriate value. Later the value is used to control whether updates to the cluster take place (for example: MachineConfig, ...).
