### ISSUE TITLE
ROSA-CP4i installation : Platform check ( AWS not supported)

### ISSUE THREAD

**Issue by mohitora** [IBM/cloud-pak-deployer#12]
**Describe the bug**
While installing cp4i using cpd-deployer, getting below error.

**To Reproduce**
All configuration used can be refered here.
https://github.com/ibm-iacs/cloud-pak-deployer/tree/ma-cp4i

**Error**
<pre>
TASK [cp4i-prepare-openshift : Validate cloud_platform is implemented] *********
Friday 10 June 2022  14:24:24 +0000 (0:00:00.081)       1:04:51.636 *********** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "cloud_platform aws is not implemented, current implemented cloud platforms are ['ibm-cloud', 'existing-ocp', 'vsphere'] "}

PLAY RECAP *********************************************************************
localhost                  : ok=366  changed=51   unreachable=0    failed=1    skipped=201  rescued=0    ignored=0   

Friday 10 June 2022  14:24:24 +0000 (0:00:00.073)       1:04:51.710 *********** 
=============================================================================== 
</pre>

**Additional context**

**Comment by yefei0423** [comment]
The issue is fixed.   Please refer to the PR: https://github.com/IBM/cloud-pak-deployer/pull/115.
