### ISSUE TITLE
Missing information in ocp-ibm-cloud-roks-nfs.yaml

### ISSUE THREAD

**Issue by hnielens** [IBM/cloud-pak-deployer#120]
When running check-only with dynamic sample ocp-ibm-cloud-roks-nfs.yaml we get below errors. There seems to be an attribute missing...

```
vsi:
infrastructure:
    keys:
    - belux-01-provision
    primary_ipv4_address: 10.231.0.196
    public_ip: true
    subnet: belux-01-subnet
    type: vpc
name: belux-01-bastion

ERROR: Attribute infrastructure.image is not defined



nfs_server:
infrastructure:
    bastion_host: belux-01-bastion
    keys:
    - belux-01-provision
    primary_ipv4_address: 10.231.0.197
    storage_folder: /data/nfs
    storage_profile: 10iops-tier
    subnet: belux-01-subnet
    type: vpc
    volume_size_gb: 1000
    zone: eu-de-1
name: belux-01-nfs

ERROR: Attribute infrastructure.image is not defined
```

**Comment by fketelaars** [comment]
@hnielens Where did you put this configuration? I checked the configuration and it appears to be ok. Can you please include the full configuration directory?

**Comment by hnielens** [comment]
@fketelaars : Above error text is a snippet of the log.

Please find attached both the _config_ and _status_ directories and their content: [data.tar.gz](https://github.com/IBM/cloud-pak-deployer/files/9644465/data.tar.gz)

```
STATUS_DIR=/data/status/sample
CONFIG_DIR=/data/config/sample
```
. The config files I copied are:
```
./cloud-pak-deployer/sample-configurations/sample-dynamic/config-sample/cp4d-451.yaml
./cloud-pak-deployer/sample-configurations/sample-dynamic/config-sample/ocp-ibm-cloud-roks-nfs.yaml
```
I cloned the cloud pak deployer repo on Sep 6

Hope this helps...

**Comment by yefei0423** [comment]
@hnielens , the issue is fixed.  Cloud you please retest it? Thanks.
