### ISSUE TITLE
Installation error on yaml script

### ISSUE THREAD

**Issue by ugurozker** [IBM/cloud-pak-deployer#140]
I tried to install cp4d-451 on existing ocp environment 4.10 and when we try to check validations script successfully finished after that, i tried to install but system returns following error:

![image](https://user-images.githubusercontent.com/108928130/191051668-c5a48bf7-9d0a-47cf-87cf-140616707754.png)

**Comment by fketelaars** [comment]
@ugurozker Looks like this was a regression. Am I correct that your OpenShift cluster is not a ROKS cluster?

**Comment by fketelaars** [comment]
Hi @ugurozker Error has been fixed. Please pull the latest changes to your local machine and rebuild the deployer image.
