### ISSUE TITLE
Bastion node airgap problem - Kubeconfig file not found

### ISSUE THREAD

**Issue by ugurozker** [IBM/cloud-pak-deployer#155]
I tried to deploy CP4D 4.5.1 version with bastion node airgapped option. It is an on-premise Openshift Cluster 4.8

1. Build Deployer with cp-deploy build command
2. Set environment variables (config, status, entitlement key)
3. Customize cpd451 and ocp-existing-ocp yaml files for installation details.
When tried to following command, error occured :
./cp-deploy.sh env download  -e env_id=plutu-01 --skip-portable-registry

![image (2)](https://user-images.githubusercontent.com/108928130/194102425-38fc3eac-83ee-42c4-93e8-8f44f6b6ff24.png)

**Comment by fketelaars** [comment]
@ugurozker Can I assume your issue has been resolved after setting the http_proxy, https_proxy environment variables? If so, I would like to add that to the documentation as special steps in case the server running the deployer is behind a proxy.

**Comment by fketelaars** [comment]
Proxy documentation was added. Closing.
