### ISSUE TITLE
Option to choose deployment type for services

### ISSUE THREAD

**Issue by chint00k** [IBM/cloud-pak-deployer#165]
Many of the Watson services have a deployment type option where a 'production' type gets deployed by default. A production deployment has at least two replicas of each pod to support production-scale workloads. This is not needed for trial or demo purposes. 

The request is to allow choosing a deployment type option, or choosing 'starter' deployment type by default.

Relevant KC link: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=discovery-installing

**Comment by fketelaars** [comment]
Fixed, all cartridges now support `installation_options` in which additional attributes (or even full JSON constructs) can be specified to be added to the `spec` of the CR.
