### ISSUE TITLE
Issue with WKC and Spark when adding a new module

### ISSUE THREAD

**Issue by ronanb3** [IBM/cloud-pak-deployer#182]
Hi,
when you install WKC, it installs Spark too (Analytics Engine powered by Apache Spark).
If I add a new module with the scripts, it works fine for the new module. But if I keep analyticsengine in removed state, it will move it.
Can you add a comment in the cp4d.yaml file about this, or add analyticsengine as a dependence in WKC ?

**Comment by fketelaars** [comment]
Hi @ronanb3. Thanks for notifying about this issue. This is a defect. I changed the code so that dependent cartridges that are not explicitly selected are no longer deleted.

**Comment by fketelaars** [comment]
Fixed
