### ISSUE TITLE
Configuration Sample for WKC in CPD 4.5.x and beyond

### ISSUE THREAD

**Issue by joe4k** [IBM/cloud-pak-deployer#200]
In Cloud Pak for Data v4.5.x, there are multiple options for installing WKC; specifically whether to include certain legacy capabilities or not, and whether to include newer functionality around lineage, quality, and factsheets.
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=catalog-preparing-install
Can we please get a sample configuration for how to select these different options with the Cloud Pak Deployer?
Thank you.

**Comment by fketelaars** [comment]
Piggybacked with #197
