### ISSUE TITLE
Given  compute_nodes: 3 but 6 nodes are getting created.

### ISSUE THREAD

**Issue by sasikanthg** [IBM/cloud-pak-deployer#202]
**Describe the bug**
Trying to install OCP and CP4D on IBM Cloud
Modified this file (https://github.com/IBM/cloud-pak-deployer/blob/main/sample-configurations/roks-ocs-cp4d/config/ocp-ibm-cloud-roks-ocs.yaml ) to install in a single zone with compute_nodes: 3. But 6 nodes are getting created in same zone (single zone)

**To Reproduce**
Refer attached ocp-ibm-cloud-roks-ocs.yaml for my modifications.

[config.zip](https://github.com/IBM/cloud-pak-deployer/files/9948658/config.zip)

**Expected behavior**
A 3 node cluster should be created instead of 6 node cluster. Refer attached screen shot

<img width="1542" alt="Screenshot 2022-11-07 at 11 48 12 AM" src="https://user-images.githubusercontent.com/111415598/200239148-0f331596-ba02-432e-95af-6538a490cf6a.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by fketelaars** [comment]
This is expected behaviour. When you select OCS (ODF) as the storage type, the deployer will add 3 additional 16x64 nodes for the ODF storage operator. This storage requires dedicated nodes.
