### ISSUE TITLE
Update wizard to work with existing OpenShift

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#204]
Make the following updates to the Wizard UI:

- [x] Update README with nvm install and build process and specific versions
- [x] Enable Existing OpenShift and make it the default
* Input fields: oc login command
- [x] Enable AWS
* Input fields: aws access key id, aws secret access key id, aws region
- [x] Move CP entitlement key input field to the Cloud Pak page
- [x] Allow updating the yaml config in an edit page before summary
- [x] If the config is already there, load the configuration from the config file (1 config file only)
- [x] Write the config file to the config directory

**Comment by yefei0423** [comment]
The task is done.  So close it.
