### ISSUE TITLE
Option to filter image architecture for mirroring

### ISSUE THREAD

**Issue by ThomasKrupski** [IBM/cloud-pak-deployer#239]
With CPD 4.6 there is now an option to mirror images only for the required hardware architecture. 
The additional flag is described here:
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=registry-mirroring-images-using-intermediary-container
Tip: Determine whether you need to modify the behavior of this command:

    By default, this command mirrors only the images that are needed for your cluster architecture. If you want to mirror the images for all supported architectures, remove the **--arch=${IMAGE_ARCH}** option.
    
    cpd-cli manage mirror-images --components=${COMPONENTS} --release=${VERSION} --target_registry=127.0.0.1:12443 **--arch=${IMAGE_ARCH**}
    
  This flag should be exposed as configurable element in the deployer configuration.

**Comment by ThomasKrupski** [comment]
Hi @arthurlaimbock, @fketelaars 
I know you are very busy but may I still ask when this feature could be implemented? We want to upgrade 4.6 at the customer and it would be very valuable if this function is given.

**Comment by fketelaars** [comment]
Implemented
