### ISSUE TITLE
Deployer currently deploys DataStage Enterprise (i.e. DS flavour without QS stages) - need to have 2 options (DS Ent Plus and DS Ent), alternatively deploy DS Enterprise Plus by default

### ISSUE THREAD

**Issue by tamara-tatian** [IBM/cloud-pak-deployer#288]
**Is your feature request related to a problem? Please describe.**
Deployer currently deploys DataStage Enterprise (i.e. the DataStage flavour that does NOT include any QS stages) 

![image](https://user-images.githubusercontent.com/111134185/210353958-763f671b-b3a2-43df-baca-b0629b098f1f.png)
![image](https://user-images.githubusercontent.com/111134185/210354015-62e90083-7407-44f5-a180-0d7dfb7166d5.png)

Would be better to deploy DS Enterprise Plus (the one WITH QS stages) by default, and best to have 2 options to choose from
 https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=datastage-installing - i.e. I'd either install
datastage_ent_plus
by default, or have 2 choices for the user in the dropdown - datastage_ent and datastage_ent_plus. 
E.g. I need the Plus version specifically.

**Describe the solution you'd like**
Have 2 choices for the user in the dropdown - one for datastage_ent (DataStage flavour without QS stages) and one for datastage_ent_plus (with QS stages/everything).
![image](https://user-images.githubusercontent.com/111134185/210354165-5e24a698-94d2-4058-a9f1-63c079076d3d.png)

**Describe alternatives you've considered**
Manual install of DataStage Enterprise Plus.... not ideal :) 

**Additional context**
See above

**Comment by tamara-tatian** [comment]
@fketelaars ^^

**Comment by fketelaars** [comment]
Fixed
