### ISSUE TITLE
Cognos Analytics instance provisioning fails

### ISSUE THREAD

**Issue by SaschaFromF** [IBM/cloud-pak-deployer#327]
**Describe the bug**
After creation of the CA instance all pods come up, but the status of the CA instance is failed.
Cognos requires a content store (here the integrated db2oltp service) and a connection to it.
Deployer configures the connection SSL encrypted but leaves the certificate blank - and this seems to be an issue.
This is verified with. CP4D 4.6.1 and 4.6.2 on ROKS

**To Reproduce**
Run the deployer with services db2 and cognos analytics installed, configure db2 instance as cognos metastore.

**Expected behavior**
Db2, Db2 Connection and CA instance will be deployed. Cognos Instance will not be working

**Screenshots**

**Additional context**
Steps to successfully create the CA instance:
- extract the SSL certificate from the db2 instance
- add the certificate text (PEM format) to the connection 
- delete existing cognos instance
- (re-) create the instance

**Comment by fketelaars** [comment]
Thank you for providing the solution steps. We have observed the failure since CP4D 4.6.1 but so far did not see any solution. I will try it out and fix using the above steps.

**Comment by fketelaars** [comment]
I have tested the steps and this seems to work. Also, the instance now shows up as "Provisioned", which used to be "Failed" all the time (despite that CA was working ok).

**Comment by fketelaars** [comment]
I've managed to automate the Db2 connection with a CA certificate. Automation went through fine. This change will be merged with the next PR.

**Comment by fketelaars** [comment]
Please note that although the above steps worked repetitively with CP4D 4.6.2, in 4.6.3 I'm seeing the same issue as before.
