### ISSUE TITLE
Pause the MachineConfig operator to disable rebooting of compute nodes

### ISSUE THREAD

**Issue by mohitora** [IBM/cloud-pak-deployer#35]
**Describe the bug**
This is while provisioning cp4d(cp4d_version: 4.0.9) over ROSA(  ocp_version: 4.8.24)  using latest version of deployer.

<pre>
TASK [cp-ocp-mco-pause : Fail if MachineConfigPool worker does not exist and not existing OpenShift or IBM Cloud] ***
Tuesday 28 June 2022  13:18:29 +0000 (0:00:00.074)       0:03:55.562 ********** 

TASK [cp-ocp-mco-pause : Pause the MachineConfig operator to disable rebooting of compute nodes] ***
Tuesday 28 June 2022  13:18:29 +0000 (0:00:00.067)       0:03:55.630 ********** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc patch --type=merge --patch='{\"spec\":{\"paused\":true}}' machineconfigpool/worker\n", "delta": "0:00:00.815561", "end": "2022-06-28 13:18:30.830015", "msg": "non-zero return code", "rc": 1, "start": "2022-06-28 13:18:30.014454", "stderr": "Error from server (Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support): admission webhook \"regular-user-validation.managed.openshift.io\" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support", "stderr_lines": ["Error from server (Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support): admission webhook \"regular-user-validation.managed.openshift.io\" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support"], "stdout": "", "stdout_lines": []}
</pre>

## Error

Error from server (Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support): admission webhook \"regular-user-validation.managed.openshift.io\" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support", "stderr_lines": ["Error from server (Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support): admission webhook \"regular-user-validation.managed.openshift.io\" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support

**Comment by mohitora** [comment]
Thanks @fketelaars . I am testing this.

**Comment by fketelaars** [comment]
There is still an open issue when applying KubeletConfig for Db2. On ROSA the MCPs can also not be labeled. Have resolved by applying Kubelet for all worker nodes in case of ROSA.
