### ISSUE TITLE
Should use storageclass ocs-storagecluster-ceph-rbd instead of ocs-storagecluster-cephfs when creating Watson Query Instance

### ISSUE THREAD

**Issue by joergre8** [IBM/cloud-pak-deployer#353]
we have deployed DV instance through deployer. Seems it has used cephfs as storageclass
Our docs recommend rbd though
Would you mind checking please?
Or can we override the  default and specify we would like to use different class?
OpenShift Data Foundation On OpenShift Data Foundation, Watson Query uses block storage. Block storage: ocs-storagecluster-ceph-rbd
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=requirements-storage

**Comment by fketelaars** [comment]
Hi @joergre8 I checked the code and the default is indeed to use file (rwx) storage class for everything. Can you revert which storages require block storage?

```
{
   "addon_type":"{{ cp4d_dv_addon_type }}",
   "display_name":"{{ _dv_instance.name }}",
   "namespace":"{{ current_cp4d_cluster.project }}",
   "addon_version":"{{ _dv_version.stdout }}",
   "create_arguments":{
      "parameters":{
         "resources.dv.requests.cpu": "{{ cp4d_dv_instance_requests_cpu }}",
         "resources.dv.requests.memory": "{{ cp4d_dv_instance_requests_memory }}",
         "image.pullPolicy": "{{ cp4d_dv_instance_pull_policy }}",
         "workerCount": "{{ cp4d_dv_instance_compute_count }}",
         "enableHostIPC": "{{ cp4d_dv_instance_enable_host_ipc }}",
{% if _storage_type == 'pwx' %}
         "persistence.storageClass": "portworx-db2-rwx-sc",
         "persistence.workerpv.storageClass": "portworx-db2-rwx-sc",
         "persistence.cachingpv.storageClass": "portworx-db2-rwx-sc",
{% else %}
         "persistence.storageClass": "{{ ocp_storage_class_file }}",
         "persistence.workerpv.storageClass": "{{ ocp_storage_class_file }}",
         "persistence.cachingpv.storageClass": "{{ ocp_storage_class_file }}",
{% endif %}
         "persistence.size": "{{ cp4d_dv_instance_persistence_storage_size }}",
         "persistence.workerpv.size": "{{ cp4d_dv_instance_persistence_compute_storage_size }}",
         "persistence.cachingpv.size": "{{ cp4d_dv_instance_persistence_caching_storage_size }}"
      },
      "resources":{
         "cpu":"{{ cp4d_dv_instance_requests_cpu }}",
         "memory":"{{ cp4d_dv_instance_requests_memory }}"
      },
      "description":"Data Virtualization",
      "metaData":{
         
      }
   },
   "transientFields":{
      
   }
}
```

**Comment by joergre8** [comment]
@fketelaars if ODF is used all storageclasses for all pvcs should point to ocs-storagecluster-ceph-rbd
being it for dvcaching as well as the workers
screenshot attached of pvc console after manual correct setup
![grafik](https://user-images.githubusercontent.com/108621395/226697578-97e98d9c-fb83-43d3-9ec8-28c92b17b540.png)

**Comment by fketelaars** [comment]
@joergre8 Understood and documented here: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=requirements-storage

We will make the following changes:

- [ ] ODF: Use block storage for all storages
- [ ] Portworx: Use block storage (rwo) for node storage and file storage (rwx) for caching
- [ ] Amazon Elastic: Use EFS for all storages
- [ ] Others: use file storage

**Comment by fketelaars** [comment]
Fixed
