### ISSUE TITLE
CP4D: 4.6.4, openshift: 4.12.9 - storageclasses.storage.k8s.io "gp2" not found.

### ISSUE THREAD

**Issue by barochiarg** [IBM/cloud-pak-deployer#369]
**Describe the bug**
storageclasses.storage.k8s.io "gp2" not found.

**To Reproduce**
1. we are trying to install CP4D 4.6.4 with Openshift 4.12.9 using cp-deployer. Installation went into the error saying that  "storageclasses.storage.k8s.io "gp2" not found.". Please find the last error message as below,

**Expected behavior**

`TASK [get-openshift-storage : Check if file storage class efs-nfs-client exists in OpenShift] ***
Friday 31 March 2023  11:54:43 +0000 (0:00:00.037)       0:28:40.142 **********

TASK [get-openshift-storage : Check if block storage class gp2 exists in OpenShift] ***
Friday 31 March 2023  11:54:43 +0000 (0:00:00.339)       0:28:40.482 **********
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc get sc gp2", "delta": "0:00:00.097054", "end": "2023-03-31 11:54:44.017378", "msg": "non-zero return code", "rc": 1, "start": "2023-03-31 11:54:43.920324", "stderr": "Error from server (NotFound): storageclasses.storage.k8s.io \"gp2\" not found", "stderr_lines": ["Error from server (NotFound): storageclasses.storage.k8s.io \"gp2\" not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=640  changed=100  unreachable=0    failed=1    skipped=276  rescued=0    ignored=0

Friday 31 March 2023  11:54:44 +0000 (0:00:00.332)       0:28:40.815 **********
===============================================================================
provision-aws : Run IPI installer for OpenShift cluster cp-deployer46-d02, logs are in /home/ec2-user/cpd-status/log/cp-deployer46-d02-create-cluster.log  1493.42s
cp4d-variables : Run list-components command --------------------------- 37.78s
nfs-storage-class : Wait 15 seconds for the dynamic NFS client to deploy -- 15.05s
openshift-download-installer : Unpack OpenShift installer -------------- 11.50s
openshift-download-installer : Unpack OpenShift installer -------------- 11.46s
cpd-cli-download : Unpack cpd-cli from /home/ec2-user/cpd-status/downloads/cpd-cli-linux-amd64.tar.gz -- 10.74s
openshift-download-installer : Download OpenShift installer "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.12/openshift-install-linux.tar.gz" --- 8.28s
aws-download-cli : Unpack aws-cli client installer ---------------------- 3.51s
openshift-download-client : Unpack OpenShift client from /home/ec2-user/cpd-status/downloads/openshift-client-linux.tar.gz-4.12 --- 3.45s
openshift-download-client : Unpack OpenShift client from /home/ec2-user/cpd-status/downloads/openshift-client-linux.tar.gz-4.12 --- 3.43s
openshift-download-client : Unpack OpenShift client from /home/ec2-user/cpd-status/downloads/openshift-client-linux.tar.gz-4.12 --- 2.57s
cpd-cli-download : Download latest cpd-cli release ---------------------- 2.56s
cloudctl-download : Unpack cloudctl from /home/ec2-user/cpd-status/downloads/cloudctl-linux-amd64.tar.gz --- 1.92s
provision-aws : Create mount target for file server cp-deployer46-d02-elastic and subnet subnet-05c7d2d610d4db25f --- 1.81s
provision-aws : Create mount target for file server cp-deployer46-d02-elastic and subnet subnet-015bca0698e9b4c41 --- 1.72s
provision-aws : Create mount target for file server cp-deployer46-d02-elastic and subnet subnet-03ed7835a97324708 --- 1.72s
cp4d-variables : Add versions details from olm-utils -------------------- 1.71s
provision-aws : Get security group for OpenShift cluster compute nodes --- 1.47s
aws-download-cli : Install aws client ----------------------------------- 1.38s
openshift-download-client : Download OpenShift client "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.12/openshift-client-linux.tar.gz" --- 1.35s`

**Desktop (please complete the following information):**
 - OS: AWS EC2 RedHat Enterprise Linux
 - AMI: RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP2

**Additional context**
please find the OCP configuration as below,

`---
global_config:
  environment_name: cp-deployer46-d02
  cloud_platform: aws
  aws_region: us-east-2

nfs_server:
- name: "{{ env_id }}-elastic"
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.12.0
  domain_name: cpdxx.ibmworkshops.com
  control_plane_flavour: m5.xlarge
  control_plane_nodes: 3
  compute_flavour: m5.4xlarge
  compute_nodes: 9
  infrastructure:
    type: self-managed
    aws_region: "{{ aws_region }}"
    use_sts: False
    multi_zone: True
    private_only: False
    machine_cidr: 10.0.0.0/16
    subnet_ids:
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
  openshift_storage:
  - storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic`

Please inform if any other details are required.

**Comment by fketelaars** [comment]
@barochiarg I reproduced the issue, you can work around it by specifying the following in your `openshift` definition:
```
  openshift_storage:
    storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic
    ocp_storage_class_block: gp3-csi
```
