### ISSUE TITLE
Add CP4WA starterset install on existing OCP

### ISSUE THREAD

**Issue by doormat18** [IBM/cloud-pak-deployer#37]
Starterset installation of CloudPak for Watson AIOps on existing OCP needs added.

This configuration is a good MVP for this functionality.

**Comment by doormat18** [comment]
Please assign issue to me. I have already started working on this.

**Comment by fketelaars** [comment]
Starter set tested, to be merged with `main` in PR https://github.com/IBM/cloud-pak-deployer/pull/56
