### ISSUE TITLE
Rosa cluster + CP4D creation failed after enabling "use_sts" flag set to True

### ISSUE THREAD

**Issue by barochiarg** [IBM/cloud-pak-deployer#371]
**Describe the bug**
Rosa cluster + CP4D creation failed after enabling "use_sts" flag set to True.

**To Reproduce**
1. trying to provision ROSA cluster with STS mode on. It's failing with below output. Please refer Additional context for the OpenShift configuration.

**Expected behavior**
TASK [openshift-login : include_tasks] *****************************************
Monday 03 April 2023  11:51:19 +0000 (0:00:00.036)       0:35:24.029 **********
included: /cloud-pak-deployer/automation-roles/99-generic/openshift/openshift-login/tasks/aws-login-ocp.yml for localhost

TASK [openshift-login : set_fact] **********************************************
Monday 03 April 2023  11:51:19 +0000 (0:00:00.053)       0:35:24.083 **********

TASK [openshift-login : include_tasks] *****************************************
Monday 03 April 2023  11:51:19 +0000 (0:00:00.054)       0:35:24.137 **********
fatal: [localhost]: FAILED! => {"reason": "'changed_when' is not a valid attribute for a IncludeRole\n\nThe error appears to be in '/cloud-pak-deployer/automation-roles/99-generic/openshift/openshift-login/tasks/aws-login-rosa-ocp.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Get cluster-admin password from the vault\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=434  changed=51   unreachable=0    failed=1    skipped=172  rescued=0    ignored=0

Monday 03 April 2023  11:51:19 +0000 (0:00:00.046)       0:35:24.184 **********
===============================================================================
provision-aws : Waiting for cluster creation to complete, logs are in /home/ec2-user/cpd-status/log/rosa-cp464-d03-create-cluster.log  1981.52s
provision-aws : Create ROSA cluster, logs can be found in /home/ec2-user/cpd-status/log/rosa-cp464-d03-create-cluster.log -- 16.34s
openshift-download-installer : Unpack OpenShift installer -------------- 11.41s
cpd-cli-download : Unpack cpd-cli from /home/ec2-user/cpd-status/downloads/cpd-cli-linux-amd64.tar.gz -- 10.88s
openshift-download-installer : Download OpenShift installer "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.12/openshift-install-linux.tar.gz" --- 9.45s
aws-download-cli : Unpack aws-cli client installer ---------------------- 3.64s
openshift-download-client : Unpack OpenShift client from /home/ec2-user/cpd-status/downloads/openshift-client-linux.tar.gz-4.12 --- 3.47s
cpd-cli-download : Download latest cpd-cli release ---------------------- 2.75s
provision-aws : Create admin user for cluster rosa-cp464-d03 ------------ 2.59s
openshift-download-client : Unpack OpenShift client from /home/ec2-user/cpd-status/downloads/openshift-client-linux.tar.gz-4.12 --- 2.45s
openshift-download-client : Download OpenShift client "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.12/openshift-client-linux.tar.gz" --- 2.20s
cloudctl-download : Unpack cloudctl from /home/ec2-user/cpd-status/downloads/cloudctl-linux-amd64.tar.gz --- 1.95s
provision-aws : Create mount target for file server rosa-cp464-d03-elastic and subnet subnet-05c7d2d610d4db25f --- 1.87s
provision-aws : Create mount target for file server rosa-cp464-d03-elastic and subnet subnet-015bca0698e9b4c41 --- 1.79s
provision-aws : Create mount target for file server rosa-cp464-d03-elastic and subnet subnet-03ed7835a97324708 --- 1.78s
provision-aws : Create NFS security group rule if not existent ---------- 1.50s
aws-download-cli : Install aws client ----------------------------------- 1.46s
aws-download-rosa : Download ROSA client "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz" --- 1.46s
provision-aws : Get security group for OpenShift cluster compute nodes --- 1.43s
provision-aws : Check if mount target for file server rosa-cp464-d03-elastic already exists --- 1.41s

====================================================================================
Deployer FAILED. Check previous messages. If command line is not returned, press

**Desktop (please complete the following information):**
 - OS: Amazon EC2 RedHat enterprise  linux

**Additional context**
Please find the below openshift configuration

---
global_config:
  environment_name: rosa-cp464-d03
  cloud_platform: aws
  aws_region: us-east-2

nfs_server:
- name: "{{ env_id }}-elastic"
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.12.7
  domain_name: ibmworkshops.com
  control_plane_flavour: m5.2xlarge
  control_plane_nodes: 3
  compute_flavour: m5.4xlarge
  compute_nodes: 6
  infrastructure:
    type: rosa
    aws_region: "{{ aws_region }}"
    use_sts: True
    multi_zone: True
    private_only: False
    machine_cidr: 10.0.0.0/16
    subnet_ids:
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
    - subnet-xx
  openshift_storage:
  - storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic
    ocp_storage_class_block: gp2

**Comment by luigimolinaro** [comment]
This is a new installation ? Could you please verify that password is setup in the vault?

**Comment by barochiarg** [comment]
This is new installation. Rosa cluster-admin password was created in the vault.

**Comment by luigimolinaro** [comment]
> This was new installation. Rosa cluster-admin password was created in the vault.

Could you please relaunch CPD with a more verbose switch and get the log.

Please verify that you are able to login to rosa with the cluster-admin password present in the vault.

**Comment by barochiarg** [comment]
I have shared verbose log 1:1 over the slack. Please inform if any other details are require
