### ISSUE TITLE
Allow update of CP4D license

### ISSUE THREAD

**Issue by semccombe** [IBM/cloud-pak-deployer#380]
After an installation of CP4D 4.6.4 using the deployer, we found that the License Service was reporting usage of "IBM Cloud Pak for Data", whereas the customer has purchased "IBM Cloud Pak for Data Enterprise Edition." 

To correct this, we used the following command to update the license:

```
cpd-cli manage apply-entitlement \
--cpd_instance_ns=${PROJECT_CPD_INSTANCE} \
--entitlement=cpd-enterprise \
--production=false
```

This command is documented here: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=manage-apply-entitlement
The CPFS License Service is documented here: https://www.ibm.com/docs/en/cpfs?topic=license-service

After this command was run, the License Server output started to correctly show usage of "IBM Cloud Pak for Data Enterprise Edition."

The request is that cp-deployer allow us to set the type of license (cpd-enterprise or cpd-standard) and whether it's a production license (true or false). 

The alternative is to run the cpd-cli command after cp-deployer has completed, in order to update the license.

**Comment by fketelaars** [comment]
Implemented change. License status page now shows:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/8166955/231724160-2af60b30-cc5a-45ac-90eb-e7a85b6ecaee.png">
