### ISSUE TITLE
Deployer of CP4D with Demo Framework failed

### ISSUE THREAD

**Issue by garastom** [IBM/cloud-pak-deployer#388]
**Describe the bug**
Deploying CP4D with demo framework I have the following error and deployer failed

FAILED - RETRYING: Waiting until catalog sources in project openshift-marketplace are ready (3 retries left).
14606
FAILED - RETRYING: Waiting until catalog sources in project openshift-marketplace are ready (2 retries left).
14607
FAILED - RETRYING: Waiting until catalog sources in project openshift-marketplace are ready (1 retries left).
14608
fatal: [localhost]: FAILED! => changed=true
14609
attempts: 60.

**Comment by fketelaars** [comment]
CP4D installs ok via demo framework.
