### ISSUE TITLE
"Error from server (NotFound): knowledgestudios.knowledgestudio.watson.ibm.com "wks" not found"

### ISSUE THREAD

**Issue by vincent-imt** [IBM/cloud-pak-deployer#443]
cp4d-464.yaml with latest clone of main branch has an error:
"Error from server (NotFound): knowledgestudios.knowledgestudio.watson.ibm.com "wks" not found"

I can see from previous issues it was once resolved.

**Comment by vincent-imt** [comment]
FYI - I manually made the 9ba201a commit change on the 1.8.0 tag and it doesn't solve the issue.
Using ocp_version: 4.10.60 and the cp4d-464.yaml file.
"Error from server (NotFound): knowledgestudios.knowledgestudio.watson.ibm.com \"wks\" not found"

**Comment by fketelaars** [comment]
@vincent-imt Did you rebuild the deployer image after making the manual change? I just merged changes with the `main` branch so you can also pull the latest changes, rebuild the image and retry.
