### ISSUE TITLE
AWS ssh to ocp master nodes

### ISSUE THREAD

**Issue by vincent-imt** [IBM/cloud-pak-deployer#445]
I am able to provision a working OpenShift cluster using AWS deployment (SNO) and (Existing VPC).

I just can't figure out how to SSH to the master nodes. To me it seems like the passwordless ssh keys are not setup on the servers? I'm not sure how I can validate that. I can confirm I can setup VPC peering and modify AWS to the point where I can ping the master nodes, and telnet to the master nodes port 22.

I tried letting the tool build a ocp-ssh-pub-key automatically when it is missing. 
I tried manually populating vault with my own public key. 
I run "oc get nodes" from the prompt "./cp_deploy env cmd" and then try to ssh to the hostname of any of the nodes.
I tried running ssh from my own server.

All the ssh attempts result in error:
replaceiwthusername@ip-replacewithip.us-west-2.compute.internal: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
I tried kubeadmin, root, ec2-user as username.

For some reason if I create ocp-ssh-pub-key manually the contents of id_rsa.pub is empty when I run ./cp_deploy env cmd.
If I let it create it automatically the contents of id_rsa.pub and id_rsa are the same value the private key in the vault.

If the cluster is offline for the first 24 hour certificate rotation, I'm trying to figure a way to access the cluster to fix the certificate issue. In my other demo instance when I create a demo instance of openshift/okd, the server the oc command continues to run even though the server is waiting for a csr to be approved, however this cloud pak deployer deployment of openshift, oc command is not able to establish connectivity when in the same situation. So the alternative I believe is to use ssh but let me know how you get around this.

Thank you!

**Comment by vincent-imt** [comment]
Sorry I finally figured it out, the username I have to use is core!
ssh -i ~/.ssh/id_ed25519 core@ip-replaceme.us-west-2.compute.internal

**Comment by fketelaars** [comment]
Hi @vincent-imt You have to use the `core` user to login to any of the control plane or compute nodes of the OpenShift cluster. I just tested this on an AWS SNO cluster and it worked for me. I let the deployer create the private and public SSH key, then copied the private ssh key to my ~/.ssh/id_rsa, set permissions and tried to SSH using the private IP address from an AWS Linux instance in the same VPC.

Once logged in as `core` you can do `sudo -i` to get `root` access.

```
[root@ip-172-16-6-184 .ssh]# ssh core@172.16.172.46
The authenticity of host '172.16.172.46 (172.16.172.46)' can't be established.
ED25519 key fingerprint is SHA256:HrKLl7INz9sLGvx+ai0z3DUVLNe1savNHRgw3ZJRZ88.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.16.172.46' (ED25519) to the list of known hosts.
Red Hat Enterprise Linux CoreOS 412.86.202305030814-0
  Part of OpenShift 4.12, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).

WARNING: Direct SSH access to machines is not recommended; instead,
make configuration changes via `machineconfig` objects:
  https://docs.openshift.com/container-platform/4.12/architecture/architecture-rhcos.html

---
```

**Comment by fketelaars** [comment]
One additional note: it's not a good idea to shut down a cluster in the first 24h or even to keep it inactive for an extended period of time as the control plane certificates will expire. Recovery is possible most of the times if you still have the original `kubeconfig` by approving the CSRs. When that file is no longer available, getting the correct `kubeconfig` file on the `master-0` node is sometimes tricky.
