### ISSUE TITLE
Default instance of Analytics Engine should be ignored when checking instances

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#457]
**Describe the bug**
```
fatal: [localhost]: FAILED! => {“changed”: false, “msg”: “Destroy was not confirmed via --confirm-destroy or global_config confirm_destroy property, will not delete Analytics Engine instance ProfHbIntrnl”}
```

**Solution**

- [ ] Skip over the `ProfHbIntrnl` instance when checking if AE instances are no longer in the config
- [ ] Check that AE will delete the instance when it is removed

**Comment by fketelaars** [comment]
To validate:

- [ ] Install CP4D 4.7 with WKC and Data quality enabled, this will install Analytics Engine with a default instance Prof..
- [ ] Re-run deployer, it will find that the ProfHbIntrnl instance cannot be deleted because destroy is not confirmed
- [ ] Update the `automation-roles/60-configure-cloud-pak/cp4d/cp4d-instance-analyticsengine/tasks/delete_analyticsengine_instance.yml` task to ignore the ProfHbIntrnl instance

**Comment by aishwaryapradeep01** [comment]
While trying to reproduce the issue, was unable to find ProfHbIntrnl instance. Steps attempted:
1. Install CP4D 4.7.0 with WKC enabled and DataQuality set to true
2. Run deployer
3. Check for the instance
4. Re-run the deployer

**Comment by fketelaars** [comment]
The `ProfHbIntrnl` instance no longer shows when listing the instances using the API. Closing.
