### ISSUE TITLE
Generate dash-formatted password

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#480]
Currently CP4D generates an admin password with 25 random characters. Change the behaviour to generate a password of the format: `RaCb3-DDJsS-HHdzs-i3GQZ`.

- [x] Create new role `99-generic/generate-password`
- [x] The role accepts 2 parameter: `_p_password_segments` (default 4) and `_p_segment_length` (default 5). The number of segments determines how many tokens the password consists of. In the above example, the password consists of 4 tokens. The segment length depicts the length of each token
- [x] The role sets a fact: `_p_generated_password`
- [x] Update the `automation-roles/50-install-cloud-pak/cp4d/cp4d-cluster/tasks/configure-cpd-admin-password.yml` task to run the `generate-password` role with default parameters when a new password must be generated

**Comment by aishwaryapradeep01** [comment]
I have tested the role created as a standalone which worked fine - it successfully generated the password in the required format. However, when I attempt to use it in the `configure-cpd-admin-password.yml`, (after building the image as well), the changes are not getting picked up, rather, the password generated is still the usual 25-characters format, unlike what was written in the role. 

I had also tried a simpler change of changing the length of the password lookup plugin from 25 to another number like 15,10,20 etc, then rebuilt the image and then tried running the deployer - I'm still seeing a 25 characters format as the password

**Comment by fketelaars** [comment]
@aishwaryapradeep01 In which branch did you create the changes so I can take a look?

**Comment by aishwaryapradeep01** [comment]
I have made a small change to test out the current setup here: https://github.com/aishwaryapradeep01/cloud-pak-deployer/tree/main

Currently, we get a 25-character long password. I just made a change to 15, to test whether changes are getting reflected as I mentioned earlier

**Comment by aishwaryapradeep01** [comment]
> I have tested the role created as a standalone which worked fine - it successfully generated the password in the required format. However, when I attempt to use it in the `configure-cpd-admin-password.yml`, (after building the image as well), the changes are not getting picked up, rather, the password generated is still the usual 25-characters format, unlike what was written in the role.
> 
> I had also tried a simpler change of changing the length of the password lookup plugin from 25 to another number like 15,10,20 etc, then rebuilt the image and then tried running the deployer - I'm still seeing a 25 characters format as the password

Thanks @fketelaars, now I understood that the reason even the simple change of changing only the password length did not work was due to the previously set vault secret
