### ISSUE TITLE
Deployment of watson-assistant and watson-discovery using version 4.7.1 and 4.7.0 fails because of secrets for MCG are currently not created.

### ISSUE THREAD

**Issue by SunilManika** [IBM/cloud-pak-deployer#493]
Deployment of watson-assistant and watson-discovery using version 4.7.1 and 4.7.0 fails because of secrets for MCG are currently not created.

One of the prerequisite before deploying is related to Multicloud Object Gateway is installed and configured. 
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=discovery-installing#cli-install__title__3

WA and WD both get stuck with below reasons
NAME   VERSION   READY   READYREASON   UPDATING   UPDATINGREASON   DEPLOYED   VERIFIED   QUIESCE   AGE
wa     4.7.0     False   Errored       False      Errored                                          7m39s
NAME   VERSION   READY   READYREASON   UPDATING   UPDATINGREASON   DEPLOYED   VERIFIED   QUIESCE   DATASTOREQUIESCE   AGE
wd     4.7.0     False   ConfigError   False      Errored                                                             7m42s

For more info, please refer to the below slack thread. 
https://ibm-analytics.slack.com/archives/C02GQMJA8JJ/p1691408462390049

**Comment by fketelaars** [comment]
Fixed
