### ISSUE TITLE
Document pull of image from quay.io

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#504]
In some situations, uses may not be able to build the deployer image on the server. Instead they could pull it from quay.io. Document the steps to pull the public image.

**Comment by luigimolinaro** [comment]
My experience on that is a customer installation under a proxy and this is the full url opened : 

`

  | quayio-production-s3.s3.amazonaws.com, art-rhcos-ci.s3.amazonaws.com, oso-rhc4tp-docker-registry.s3-us-west-2.amazonaws.com, dseasb33srnrn.cloudfront.net, docker.io, production.cloudflare.docker.com, registry.redhat.io, quay.io, docker-na-public.artifactory.swg-devops.com, openshift.org, infogw.api.openshift.com, cloud.redhat.com, mirror.openshift.com, storage.googleapis.com, api.openshift.com, docker.com, www.redhat.com, stg-edge-cdt.eventsgslb.ibm.com, icr.io, www.ibm.com, redhat.com, rhc4tp-prod-z8cxf-image-registry-us-east-1-evenkyleffocxqvofrk.s3.dualstack.us-east-1.amazonaws.com, gcr.io, cloud.google.com, www.okd.io, esupport.ibm.com, www.ecurep.ibm.com, www.secure.ecurep.ibm.com, twwwecurep.mainz.de.ibm.com, bluepages.ibm.com, login.microsoftonline.com, portal.azure.com, core.windows.net, s3.jp-tok.cloud-object-storage.appdomain.cloud, s3.us-west-2.amazonaws.com, github.com, cdn03.quay.io, rpm.releases.hashicorp.com, aliyuncs.com, ec2.amazonaws.com, events.amazonaws.com, iam.amazonaws.com, route53.amazonaws.com, s3.amazonaws.com, sts.amazonaws.com, tagging.us-east-1.amazonaws.com, googleapis.com, accounts.google.com, management.azure.com, blob.core.windows.net, dl.fedoraproject.org, mirrors.fedoraproject.org, fedora.mirrorservice.org, pypi.org, galaxy.ansible.com, ocsp.digicert.com, raw.githubusercontent.com, objects.githubusercontent.com
-- | --



[quayio-production-s3.s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__quayio-2Dproduction-2Ds3.s3.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=nhhYmuayUe0QFBBpekoyHb0DlwgglnncY3a6-2oOsME&e=), [art-rhcos-ci.s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__art-2Drhcos-2Dci.s3.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=ZkxTLWKdieiPpIn2ZMwiAObtT-VN4Iug3FVmQiKo3O4&e=), [oso-rhc4tp-docker-registry.s3-us-west-2.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__oso-2Drhc4tp-2Ddocker-2Dregistry.s3-2Dus-2Dwest-2D2.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=IcNLnjY3JFfvyqymI5tRhbRfM5t8q_nGocXfTZfcl38&e=), [dseasb33srnrn.cloudfront.net](https://urldefense.proofpoint.com/v2/url?u=http-3A__dseasb33srnrn.cloudfront.net&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=X5qRiKLjASWCUPer4jlELcn4TmrDWkRJ7lIbpXitppE&e=), [docker.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__docker.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=d9fHaNLLOtoBM8W2SUlBt0gNRpfrapzFhdrBueymfUs&e=), [production.cloudflare.docker.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__production.cloudflare.docker.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=WM_8idcekwOq_y2oC_0eb1U259qJgYqUnNi3qCJbfYk&e=), [registry.redhat.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__registry.redhat.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=rek0vgYKlsMpS__pgmGyNWgp_5I4F6o3_4PYGh2o5N8&e=), [quay.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__quay.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=WFmvWNlPJAiDjNx-82zXtSLlNKHrojkjXeu0OLBreXU&e=), [docker-na-public.artifactory.swg-devops.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__docker-2Dna-2Dpublic.artifactory.swg-2Ddevops.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=PF6FnRbszie8edjvyTUA2GrGl78S6R6s4jjrnVl0Xl8&e=), [openshift.org](https://urldefense.proofpoint.com/v2/url?u=http-3A__openshift.org&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=hwPvCFiYe9zEjCjS_qlRsTKMlkj53AFrEu0qs2lBAgo&e=), [infogw.api.openshift.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__infogw.api.openshift.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=iwKuiO3T_ZTa7OeP_DpgcMQAjNvOVz-0potKaT9cWQk&e=), [cloud.redhat.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__cloud.redhat.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=JwWN-EZjXFlJKh7Z49btLpHU_RpQldMo54f6P7vQzSo&e=), [mirror.openshift.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__mirror.openshift.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=uOqADezyVDph7VMJMbCEC7R_3etUvVBBeYMMWd_jWaE&e=), [storage.googleapis.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__storage.googleapis.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=Wya61yRLhU2ipvZzRnz8TSI6oScMs9hjscdVC7GK_8k&e=), [api.openshift.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__api.openshift.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=9fKAkc-WjjkFDfoCqaVlkK8Oo3LO9LU6OMrkHQ-2Jq0&e=), [docker.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__docker.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=gbbwbMEXg2l0wiv8Gv2148jIBoOuojz2xzgmH83mUQA&e=), [www.redhat.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__www.redhat.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=15UITvKSvWNyd262Zj5euPSOChLcTRVT2I_h1yIwirs&e=), [stg-edge-cdt.eventsgslb.ibm.com](http://stg-edge-cdt.eventsgslb.ibm.com/), [icr.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__icr.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=IwYcQTx0knGbUBMDxUf70x0_x_cvBk6cxKYEQHIDlb8&e=), [www.ibm.com](http://www.ibm.com/), [redhat.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__redhat.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=ob7LJJQtQJ3LrCt1QViUucixxontjOgHOyIR9P9nMPo&e=), [rhc4tp-prod-z8cxf-image-registry-us-east-1-evenkyleffocxqvofrk.s3.dualstack.us-east-1.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__rhc4tp-2Dprod-2Dz8cxf-2Dimage-2Dregistry-2Dus-2Deast-2D1-2Devenkyleffocxqvofrk.s3.dualstack.us-2Deast-2D1.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=oDcHKFiHl02hatmpoZNSznG1eGcbEl5CQlpSYFTT8MU&e=), [gcr.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__gcr.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=zMr0z8AeqDEDuzSXmdZucXomq1b5028upj4ekT5_F3s&e=), [cloud.google.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__cloud.google.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=pkJvPde_XrzOTA2Yo7eTFTkYty2AmwIdGBCALQh1-tM&e=), [www.okd.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__www.okd.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=kr7ZT6mbE7jqSgarfakqEPQnRS5qaOvvi3_8-ozGHU8&e=), [esupport.ibm.com](http://esupport.ibm.com/), [www.ecurep.ibm.com](http://www.ecurep.ibm.com/), [www.secure.ecurep.ibm.com](http://www.secure.ecurep.ibm.com/), [twwwecurep.mainz.de.ibm.com](http://twwwecurep.mainz.de.ibm.com/), [bluepages.ibm.com](http://bluepages.ibm.com/), [login.microsoftonline.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__login.microsoftonline.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=jf8ELdHAWBNG_VvFzkL8RLUuqJ16gy-e-dC86b4V9hw&e=), [portal.azure.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__portal.azure.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=LjdhV27dwMMW5MUPJc1VUexIuVoqBsV6yMl2qKUa_p8&e=), [core.windows.net](https://urldefense.proofpoint.com/v2/url?u=http-3A__core.windows.net&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=5QuRdZz8YLQYD-Pr_O5CDYqv9g2BeGghpDeCNaJIa3o&e=), s3.jp-tok.cloud-object-storage.appdomain.cloud, [s3.us-west-2.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.us-2Dwest-2D2.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=lEobTARe8Hwyk9BkUsfq-f0drkrGO8q4zxzeiYlOuP8&e=), [github.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__github.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=RDhtNoHLIa3j-X65eBLAUVqFD7eQnhtlpEC6zamQud4&e=), [cdn03.quay.io](https://urldefense.proofpoint.com/v2/url?u=http-3A__cdn03.quay.io&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=PempPXwLRYIkT4lASPcBPtS3hahrjdNkEiczpA0JMfI&e=), [rpm.releases.hashicorp.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__rpm.releases.hashicorp.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=kKk7-9nvcRzSSmb3IsaOiAQoaei3jMLuJs7rB32vaVg&e=), [aliyuncs.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__aliyuncs.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=B3HhQtOZOuwT0BqxZmW9-cpGeIaXUGt7unFjQi9YQ-M&e=), [ec2.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__ec2.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=o_g_QVpDqeEJ067_5wb1yCO1RcBizpARSnyEvbinCp4&e=), [events.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__events.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=Eqwr2iKz3zNv-9155d633sm11475D4klW7pJVz3dzMM&e=), [iam.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__iam.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=1xOW7VmK1FV0SvhdAc6GJsB91bvPcwt-poecTrP3qnA&e=), [route53.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__route53.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=uSR6giPKGsPIPopiT09rwoQ682UikH9Q0KY5KAwNvrY&e=), [s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=-GhAY-WkRCpfFIcguLvUk2FV4QMX_ymvcXMmtIFoEuM&e=), [sts.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__sts.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=rBf5aTRGRJ7bsoyBcRw7xbG-YqbxGBLUq6VoXK2IWns&e=), [tagging.us-east-1.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__tagging.us-2Deast-2D1.amazonaws.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=oiT6yMmcDOGdsVcjpzT5T9fLPI0oWk5uxE3xcWOGXWQ&e=), [googleapis.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__googleapis.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=1jO2YmjhaV8os-eJ_WxSEBCMLzvocCLMFW_hjWwq45U&e=), [accounts.google.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__accounts.google.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=BgvWNPSEp07o8PnVZoJTZSkHINuXoL5mAjbBTVH9FbY&e=), [management.azure.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__management.azure.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=-VWaQVdhLzbKCZYjknXbqz8P4YaFwdDUUj9TZyvvG74&e=), [blob.core.windows.net](https://urldefense.proofpoint.com/v2/url?u=http-3A__blob.core.windows.net&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=7oWVwUBD8PqpMJVRbU41sB1HtzYTnFoIPcQpqUUiyJQ&e=), [dl.fedoraproject.org](https://urldefense.proofpoint.com/v2/url?u=http-3A__dl.fedoraproject.org&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=bOytHkevdWbT6l8u07A5g77vjym_FVBALlNyHpyhE-w&e=), [mirrors.fedoraproject.org](https://urldefense.proofpoint.com/v2/url?u=http-3A__mirrors.fedoraproject.org&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=LI__YO4NBzhYTTnAM47v5CAyNr7DUQdCPz63U6TzCko&e=), [fedora.mirrorservice.org](https://urldefense.proofpoint.com/v2/url?u=http-3A__fedora.mirrorservice.org&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=mwoM8vfXYhlLv6etJdrpwStg4xelsAKbzaPOOfdoiI4&e=), [pypi.org](https://urldefense.proofpoint.com/v2/url?u=http-3A__pypi.org&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=imYHwiX-HABBmG34awvEIFefH8Af_bU6gPWcWtruOY8&e=), [galaxy.ansible.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__galaxy.ansible.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=2PjL77njHsnDESCuPnVUBAhtiH5qmPxD3esipAUNWvA&e=), [ocsp.digicert.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__ocsp.digicert.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=GLIwC740cWOyg_slmGKeMTuSvToXhtDHhc2Ua06sILE&e=), [raw.githubusercontent.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__raw.githubusercontent.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=6Klh0hiXrACs6jG_A-iTBojHizs8dStj_Bm-wYpta2Q&e=), [objects.githubusercontent.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__objects.githubusercontent.com&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=fFKlbtA4IkEBdRzAQy1GxGO05Vvej6GMJWeiULviFQg&m=MVelhTAyS0m32jr1o9IntZgMkRhEQCboHARfbboJ1qHF9krfkF20XZHesnGmR8vS&s=6qC_G20pA1lv68TuYiMR4ZWdQEfs-UVF1__wxWr5f28&e=)`

**Comment by luigimolinaro** [comment]
In my experience thereis a lot of url used form the deployer.
I tried to compile "Cloud Pak Deployer" under a Proxy Enviroment and this is the list of the opened urls

`
1. quayio-production-s3.s3.amazonaws.com
2. art-rhcos-ci.s3.amazonaws.com
3. oso-rhc4tp-docker-registry.s3-us-west-2.amazonaws.com
4. dseasb33srnrn.cloudfront.net
5. docker.io
6. production.cloudflare.docker.com
7. registry.redhat.io
8. quay.io
9. docker-na-public.artifactory.swg-devops.com
10. openshift.org
11. infogw.api.openshift.com
12. cloud.redhat.com
13. mirror.openshift.com
14. storage.googleapis.com
15. api.openshift.com
16. docker.com
17. www.redhat.com
18. stg-edge-cdt.eventsgslb.ibm.com
19. icr.io
20. www.ibm.com
21. redhat.com
22. rhc4tp-prod-z8cxf-image-registry-us-east-1-evenkyleffocxqvofrk.s3.dualstack.us-east-1.amazonaws.com
23. gcr.io
24. cloud.google.com
25. www.okd.io
26. esupport.ibm.com
27. www.ecurep.ibm.com
28. www.secure.ecurep.ibm.com
29. twwwecurep.mainz.de.ibm.com
30. bluepages.ibm.com
31. login.microsoftonline.com
32. portal.azure.com
33. core.windows.net
34. s3.jp-tok.cloud-object-storage.appdomain.cloud
35. s3.us-west-2.amazonaws.com
36. github.com
37. cdn03.quay.io
38. rpm.releases.hashicorp.com
39. aliyuncs.com
40. ec2.amazonaws.com
41. events.amazonaws.com
42. iam.amazonaws.com
43. route53.amazonaws.com
44. s3.amazonaws.com
45. sts.amazonaws.com
46. tagging.us-east-1.amazonaws.com
47. googleapis.com
48. accounts.google.com
49. management.azure.com
50. blob.core.windows.net
51. dl.fedoraproject.org
52. mirrors.fedoraproject.org
53. fedora.mirrorservice.org
54. pypi.org
55. galaxy.ansible.com
56. ocsp.digicert.com
57. raw.githubusercontent.com
58. objects.githubusercontent.com
`

Another method usefully in this scenario is **build deployer in a computer allowed** and copy the raw image using for example docker cp : 

### example

## Save the Docker image as a tar file in machine 1
`docker save -o app_build_001.tar artifactory.rc.com/repo/test_app_snapshots:app_build_001`

## Copy the tar file to machine 2
`scp app_build_001.tar remote_username@172.10.10.2:/remote/directory`

## Import image into machine 2
`docker load -i <path to image tar file>`
