### ISSUE TITLE
WKC installation is get failed

### ISSUE THREAD

**Issue by barochiarg** [IBM/cloud-pak-deployer#508]
**Describe the bug**
WKC installation is get failed

We are trying to install WKC, WSL. We are facing issues, 2 pods are continuously in loop of kill, start and pending loop(please refer attached screen shot).  while investigation we found that there is a pod "zen-database-core-xx" restart on every few internal and it's having following error message in the log. not sure if there is a dependency wrt the issue. We are unable to install WKC currently using cp-deployer. May we get some help on this?

_time="2023/08/25 11:34:39" level=info msg="Attempting to migrating data from couchdb if any..." func=zen-databases-core/pkg/generated/restapi.migrateMetadata file="/go/src/zen-databases-core/pkg/generated/restapi/configure_databases.go:206"
time="2023/08/25 11:34:39" level=error msg="secrets \"couchdb-secrets\" not found" func=zen-databases-core/pkg/impl/utils.GetSecretInNamespace file="/go/src/zen-databases-core/pkg/impl/utils/couchdb.go:77"
time="2023/08/25 11:34:39" level=error msg="secrets \"couchdb-secrets\" not found" func=zen-databases-core/pkg/impl/utils.GetSecretInNamespace file="/go/src/zen-databases-core/pkg/impl/utils/couchdb.go:77"
time="2023/08/25 11:34:39" level=info msg="No couchdb info found... nothing to migrate" func=zen-databases-core/pkg/generated/restapi.migrateMetadata file="/go/src/zen-databases-core/pkg/generated/restapi/configure_databases.go:243"
2023/08/25 11:34:39 Serving databases at https://[::]:3025_

we have seen this behaviour in both 4.6.6 an 4.7.0. we are seeing the following event forbidden sysctl: "kernel.shmmni" not allowlisted  for the pod c-db2oltp-wkc-db2u-0

**Comment by fketelaars** [comment]
Fixed:
* Only a single KubeletConfig will be created (multiple KubeletConfigs not supported by MachineConfig)
* Dependent on OCP version, the KubeletConfig will include podPidsLimit
* Existing obsolete KubeletConfig is deleted if found

**Comment by fketelaars** [comment]
Issue fixed.
