### ISSUE TITLE
Simplify deployment steps

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#537]
**Is your feature request related to a problem? Please describe.**
Deployer offers a myriad of configuration options and sometimes it's difficult for users to navigate. Simplify the steps to focus on installing the deployer and then running it with default configuration files. For more advanced users, provide links to the documents with advanced configuration steps.

**Comment by luigimolinaro** [comment]
Yes this is a super intuition:
Would be great if you can use something like that : https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=information-setting-up-installation-environment-variables 

Experienced user can build their own.
