### ISSUE TITLE
Starting in 4.7.3 - Manta is installed as a service

### ISSUE THREAD

**Issue by markhickok** [IBM/cloud-pak-deployer#538]
**Is your feature request related to a problem? Please describe.**
Effective with v 4.7.3 - Manta add-on in WKC is now a service install.

https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=lineage-installing

![image](https://github.com/IBM/cloud-pak-deployer/assets/41272221/c7c81b23-101f-4cdf-b2d8-d252843b0e18)

**Describe the solution you'd like**
Add MANTA service install to deployer

**Describe alternatives you've considered**
Eff with 4.7.3 there are no other alternatives.  It has to be installed as a service.

**Additional context**

**Comment by fketelaars** [comment]
Fixed
