### ISSUE TITLE
Add version check logic to implement version-specific install steps. Example: wkc-iis-scc is no longer used in CPD v4.7.x

### ISSUE THREAD

**Issue by MrStutterZ** [IBM/cloud-pak-deployer#556]
**Describe the bug**
==========================================
When installing WKC in CPD v4.7.x, the custom scc named 'wkc-iis-scc' should no longer be created.

In CPD v4.6.x documentation, users installing WKC on CPD are instructed (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=cluster-creating-custom-sccs-services) to create one custom SCC manually (wkc-iis-scc), as described here: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=services-creating-watson-knowledge-catalog-scc.

Instead, users installing WKC (and other services) in CPD v4.7.x are instructed (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=settings-changing-kernel-parameter) to make a decision (via config map) that determines how Db2U runs for all services on the cluster. The 'db2u-product-cm' has a variable ('DB2U_RUN_WITH_LIMITED_PRIVS') that determines which objects/resources are created during the install (kubeletconfig, tuned, and/or neither).

Some version check logic should be added to the deployer to execute appropriate steps to follow version-specific documentation.

**To Reproduce**
==========================================
Install WKC and CPD v4.7.x. When checking the system after the installation is successful, look at the resources in the cluster. You will see the custom WKC SCC which should no longer be used.

**Expected behavior**
==========================================
We should not see the 'manually' created custom SCC for WKC after performing an install of CPD v4.7.x software on a 'fresh' cluster.

**Screenshots**
==========================================
None.

**Desktop (please complete the following information):**
==========================================
Not Applicable.

**Smartphone (please complete the following information):**
==========================================
Not Applicable.

**Additional context**
==========================================
None.

**Comment by fketelaars** [comment]
Changes:
- [ ] Implement `db2u-product-cm` config map for CP4D 4.7+, set default to "privileged" (no limited privs) install of Db2
- [ ] Only create CM when a db2u-dependent service is installed
- [ ] Let operator handle the creation of SCCs, dependent on "privileged" setting
- [ ] Create Tuned resource only for non-privileged installs and when service needing is installed
- [ ] Create KubeletConfig only for non-privileged installs and when service needing it is installed

Tesing:
- [ ] Test CP4D 4.7 install with WKC and "privileged", check configmap and absence of SCC
- [ ] Test CP4D 4.7 install with WKC and "non-privileged", check configmap and presence of SCC and KubeletConfig
- [ ] Test CP4D 4.7 install with DV and "non-privileged", check configmap and presence of Tuned
- [ ] Test CP4D 4.6 install with WKC and "privileged", check custom spec in WKC resource
- [ ] Test CP4D 4.6 install with WKC and "non-privileged", check presence of SCC and KubeletConfig
