### ISSUE TITLE
Ability to run custom scripts through the cloud-pak-crontab-ds framework

### ISSUE THREAD

**Issue by semccombe** [IBM/cloud-pak-deployer#572]
**Is your feature request related to a problem? Please describe.**
During a recent engagement, we needed to make additional changes to the RHCOS node-level configuration for the crio daemon. 

We replicated the two CMs used by cloud-pak-deployer - namely cloud-pak-node-fix-config and cloud-pak-node-fix-scripts - to create a second pair of CMs. These were then mounted into the DS pod through an edit of the DS YAML, and were eventually copied into the RHCOS node by the DS command. 

Finally, we made a manual change to the cloud-pak-node-fix.sh script at the node level to call our custom script. The next time the timer ran, our config change was copied to the crio config directory.  We did this manually so as to reduce the risk of adding bad config to crio. 

**Describe the solution you'd like**
I propose a generalization of this process, to be able to define and call custom scripts with the DS/CM/timer framework already used to configure ICSP and entitlements for ROKS clusters. 

For this cluster, it would have been next to impossible to access the nodes without debug access. So, it was important not to introduce bad crio configuration to the node. If this capability were introduced, it may be important to test the `systemctl restart crio` command to ensure that crio comes back up successfully; if not a rollback may be in order. 

**Describe alternatives you've considered**
This is the solution we quickly came up with to introduce a patch to the cluster. Not sure if this is the best approach.

**Comment by fketelaars** [comment]
Sorry, was incorrectly closed.
