### ISSUE TITLE
Support for installation of the latest CP4I 2023.4.1 in shared or dedicated namespace

### ISSUE THREAD

**Issue by gasgithub** [IBM/cloud-pak-deployer#603]
Latest cp4i installation differs from previous versions as CS services must be deployed before as pre-req.
It should also support "single namespace" installation.

It would be great if deployer would allow to choose whether to install in shared (openshift-operators) or dedicated namespace.
Dedicated namespece installation would allow better compatibility when multiple CPaks are installed on the single cluster.

**Comment by fketelaars** [comment]
Suggestions after first code review and trial:
* Currently, you're installing Red Hat certification manager, whereas CP4D standardizes on the IBM certification manager. Suggest to use role `cp-fs-cluster-components` to install the certificate manager and license server in their default namespaces (`ibm-cert-manager` and `ibm-licensing`). The role has a mandatory `_p_cp4d_version` parameter but we can quite easily find the latest version in the container and default to this.
* I think that the default installation mode for CP4INT should be **specific namespace mode** and that use of `ibm-common-services` should be avoided. Suggestion is to use `cp4i-operators` for the operators controlling the specific version of CP4INT.
* Foundational Services operator can also be installed in the `cp4i-operators` namespace.
* For discussion as it does not align with the documentation: catalog sources are now installed in `openshift-marketplace`. In CP4D, they are now installed in the operator namespace which gives the ability to have multiple installations with different releases. Probably needs some testing as also the Subscriptions need to be adjusted accordingly.
