### ISSUE TITLE
this doesnt work !

### ISSUE THREAD

**Issue by XAV-01** [IBM/cloud-pak-deployer#615]
**Describe the bug**
doing all you said, bit failing to dfeploy cp4d 4.8.1

follow instruction and get stucl with vert-manager failure
 

**Expected behavior**
would be nice if it work

**Screenshots**
void

**Additional context**
Sick of it

**Comment by fketelaars** [comment]
@XAV-01 can you please provide more info regarding the error you’re receiving. “Vertex” is not something we’ve seen with deployer. If you work for IBM (can’t tell by your GitHub name), please ping me on Slack to discuss.

**Comment by fketelaars** [comment]
Closing issue as there are no details about the error. Please re-open with additional info if relevant.
