### ISSUE TITLE
Watson Assistant install fails on 4.8.x

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#623]
**Describe the bug**
Installing watson assistant cartridge fails on 4.8.x as it is missing the require Knative operator

https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=manage-deploy-knative-eventing
If you plan to install the IBM® watsonx Assistant service on IBM Cloud Pak® for Data, you must install the following software on your cluster to set up a message broker for IBM watsonx Assistant.

- Red Hat OpenShift Serverless Knative Eventing
- IBM Events

During deployment without the pre reqs installed the clu_training component fails to deploy and is stuck in a cycle.

**To Reproduce**
Set watson assistant to installed in the deployer yaml

**Comment by techietav** [comment]
I have confirmed that installing knative eventing resolves this problem.

I managed to get WA installed by following this.
https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=software-installing-red-hat-openshift-serverless-knative-eventing

cpd-cli manage authorize-instance-topology \
--release=${VERSION} \
--cpd_operator_ns=ibm-knative-events \
--cpd_instance_ns=knative-eventing

cpd-cli manage setup-instance-topology \
--release=${VERSION} \
--cpd_operator_ns=ibm-knative-events \
--cpd_instance_ns=knative-eventing \
--license_acceptance=true

cpd-cli manage deploy-knative-eventing \
--release=${VERSION} \
--block_storage_class=${STG_CLASS_BLOCK}

**Comment by techietav** [comment]
I also discovered that I in ibm-knative-events namespace > IBM NamespaceScope Operator I needed to update the value of MultiNamespace to true as it was in error.
```
spec
  installModes:
    type: MultiNamespace
    - supported: true

```

**Comment by fketelaars** [comment]
@techietav My installation finished ok without having to make any further changes.

**Comment by techietav** [comment]
The CP4D documentation says to use those namespaces so I followed that.

**Comment by fketelaars** [comment]
I see: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=software-installing-red-hat-openshift-serverless-knative-eventing. I didn't run these steps explicitly on a 4.8.1 installation and found that he OperatorGroup was created correctly:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"annotations":{},"name":"common-service","namespace":"ibm-knative-events"},"spec":{"targetNamespaces":["ibm-knative-events","knative-eventing"],"upgradeStrategy":"Default"}}
    olm.providedAPIs: Kafka.v1beta1.ibmevents.ibm.com,KafkaBridge.v1alpha1.ibmevents.ibm.com,KafkaBridge.v1beta2.ibmevents.ibm.com,KafkaConnect.v1beta1.ibmevents.ibm.com,KafkaConnector.v1alpha1.ibmevents.ibm.com,KafkaMirrorMaker.v1beta1.ibmevents.ibm.com,KafkaMirrorMaker2.v1alpha1.ibmevents.ibm.com,KafkaRebalance.v1alpha1.ibmevents.ibm.com,KafkaTopic.v1beta1.ibmevents.ibm.com,KafkaUser.v1beta1.ibmevents.ibm.com
  creationTimestamp: "2024-01-26T07:12:04Z"
  generation: 1
  name: common-service
  namespace: ibm-knative-events
  resourceVersion: "38959423"
  uid: efd455c5-d429-4b89-ac95-2660dda86f02
spec:
  targetNamespaces:
  - ibm-knative-events
  - knative-eventing
  upgradeStrategy: Default
status:
  lastUpdated: "2024-01-26T07:12:04Z"
  namespaces:
  - knative-eventing
  - ibm-knative-events
```

It looks like the steps are redundant.

**Comment by gasgithub** [comment]
> I have confirmed that installing knative eventing resolves this problem.
> 
> I managed to get WA installed by following this. https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=software-installing-red-hat-openshift-serverless-knative-eventing
> 
> cpd-cli manage authorize-instance-topology --release=${VERSION} --cpd_operator_ns=ibm-knative-events --cpd_instance_ns=knative-eventing
> 
> cpd-cli manage setup-instance-topology --release=${VERSION} --cpd_operator_ns=ibm-knative-events --cpd_instance_ns=knative-eventing --license_acceptance=true
> 
> cpd-cli manage deploy-knative-eventing --release=${VERSION} --block_storage_class=${STG_CLASS_BLOCK}

I had to do these steps on the cp4d  4.8.0. I didnt test the newer versions yet
