### ISSUE TITLE
Building cloud-pak-deployer image fails on Windows in WSL2

### ISSUE THREAD

**Issue by m-g-k** [IBM/cloud-pak-deployer#627]
When running `./cp-deploy.sh build` on WSL2 on Windows it fails. This error is output:

```
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.3.1
    Uninstalling pip-23.3.1:
ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'platformdirs'
```

This is because the `pip3 install --upgrade pip` in the `Dockerfile` fails. Removing this line allows the container build to complete.

**Comment by fketelaars** [comment]
Done as part of #628
