### ISSUE TITLE
Kubelet Config not created when installing WKC in limited privileges mode

### ISSUE THREAD

**Issue by israel-a-vizcarra** [IBM/cloud-pak-deployer#630]
**Describe the bug**
Kubelet Config not created when installing WKC in limited privileges mode

**To Reproduce**
1. Setup configuration file with `db2u_limited_privileges: True`
2. Run cp-deployer installation for core CPD and WKC 

**Expected behavior**
Installation should complete successfully

oc version: 4.12.47
cp4d installation : CPD 4.8.1 (GA)
Cartridges to be installed WKC
Recently deployed techzone cluster

**Additional context**
WKC failed status
```
israel@Israels-MacBook-Pro cloud-pak-deployer % oc get wkc
NAME     VERSION   RECONCILED   STATUS       AGE
wkc-cr   4.8.1                  Failed   4h18m
```

Pods in a bad state
```
 INFO:    ========================================================
 INFO:    >     SUMMARY OF PODS FOUND IN AN UNHEALTHY STATE       
 INFO:    ========================================================
 INFO:    c-db2oltp-wkc-db2u-0                                              0/1   SysctlForbidden   0                0s      <none>         worker-1   <none>   <none>
 ERROR:   wkc-db2u-init-62sxt                                               0/1   Error             0                113m    10.131.2.183   worker-3   <none>   <none>
 ERROR:   wkc-db2u-init-8zr45                                               0/1   Error             0                110m    10.131.0.56    worker-2   <none>   <none>
 ERROR:   wkc-db2u-init-vddhs                                               0/1   Error             0                107m    10.131.0.65    worker-2   <none>   <none>
 ERROR:   wkc-db2u-init-w6rp5                                               0/1   Error             0                103m    10.131.2.190   worker-3   <none>   <none>
```

Checked the Configmap was present

```
israel@Israels-MacBook-Pro cloud-pak-deployer % oc -n cpd-operator get cm db2u-product-cm  -oyaml
apiVersion: v1
data:
  DB2U_RUN_WITH_LIMITED_PRIVS: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB2U_RUN_WITH_LIMITED_PRIVS":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"db2u-product-cm","namespace":"cpd-operator"}}
  creationTimestamp: "2024-01-25T01:27:46Z"
  name: db2u-product-cm
  namespace: cpd-operator
  resourceVersion: "123403"
  uid: 60f91b5b-84ba-4aeb-b943-d6f84da1cbd8
```

The resource missing for the installation to be successful was the KubeletConfig
```
israel@Israels-MacBook-Pro cloud-pak-deployer % oc get kubeletconfigs -A
No resources found
```
[cloud-pak-deployer.log](https://github.com/IBM/cloud-pak-deployer/files/14058462/cloud-pak-deployer.log)
[config_file.txt](https://github.com/IBM/cloud-pak-deployer/files/14058489/config_file.txt)

**Comment by fketelaars** [comment]
HI @israel-a-vizcarra I have run the deployer with the same version and with the `db2u_limited_privileges` set to `True` and in my case the `kubeletconfig` is created.

```
[fketelaars@ip-10-1-0-110 cloud-pak-deployer]$ oc get kubeletconfig
NAME           AGE
db2u-kubelet   17h
```

Can you please ping me so I can take a look at your cluster?

**Comment by israel-a-vizcarra** [comment]
Hi @fketelaars .

This was a temporary cluster, so its being scrapped already, I have also deployed WKC without a problem in limited mode in other envs, so I assume this was an environmental issue, I think we can close the issue and reopen it if the issue is hit again. Right now im not able to reproduce

**Comment by fketelaars** [comment]
Agreed. Thank you.
