### ISSUE TITLE
 Be able to add a Watson Assistant instance via deployer

### ISSUE THREAD

**Issue by gasgithub** [IBM/cloud-pak-deployer#631]
I'd like to automate WA instance creation.
Currently deployer can install the WA service, but user have to manually create new instance of the service.

**Describe the solution you'd like**
I'd like to have additional set of the parameters in the pipeline that would be used to create instance of WA after the service is installed.

**Describe alternatives you've considered**
As alternative user can manually create new instance after CP4D deployment. The problem is that it is manual task and if one would like to have complete, automated repeatable process to setup WA in CP4D, it is not possible and would require additional tooling.

**Comment by fketelaars** [comment]
Added creating instance for:
- DMC
- Watson Assistant
- Watson Discovery
