### ISSUE TITLE
Failing Watson Assistant or Watson Discovery on self-managed cluster on AWS

### ISSUE THREAD

**Issue by barochiarg** [IBM/cloud-pak-deployer#639]
**Describe the bug**
While installing Watson Assistant or Watson Discovery on self-managed cluster on AWS, it has been observed that MCG creation get stuck. It unable to create secret "noobaa-aws-cloud-creds-secret" in "openshift-storage".

**To Reproduce**
1. Create self-manage cluster on AWS using access and secret access key
2. Create Single Node Cluster by supplying 1 master node and 0 worker node
3. Choose to install Watson Assistant and Watson Discovery

**Expected behavior**
Watson Assistant and Watson Discovery should install

**Desktop (please complete the following information):**
- CPD 4.8.2
- OpenShift version 4.12.49

**Comment by fketelaars** [comment]
Fixed as part of #577
