### ISSUE TITLE
NFD Operator does not install

### ISSUE THREAD

**Issue by chechuironman** [IBM/cloud-pak-deployer#708]
The operatorgroup in the NFD operator tries to install in all ns, but seems is not allowed by the operator. Need to be corrected to this 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nfd-og
  namespace: openshift-nfd
spec:
  upgradeStrategy: Default
  targetNamespaces:
  - openshift-nfd

**Comment by fketelaars** [comment]
Fixed.
