### ISSUE TITLE
Simplification of AWS Storage Classes now missing gp2-csi and gp3-csi classes

### ISSUE THREAD

**Issue by Alan111S** [IBM/cloud-pak-deployer#715]
**Describe the bug**
When running the deployer on AWS, it failed with the following failure:-

```
TASK [get-openshift-storage : Check if block storage class exists in OpenShift] ***
Wednesday 15 May 2024  13:51:33 +0000 (0:00:00.568)       0:40:08.782 *********
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc get sc gp2", "delta": "0:00:00.187320", "end": "2024-05-15 13:51:33.869749", "msg": "non-zero return code", "rc": 1, "start": "2024-05-15 13:51:33.682429", "stderr": "Error from server (NotFound): storageclasses.storage.k8s.io \"gp2\" not found", "stderr_lines": ["Error from server (NotFound): storageclasses.storage.k8s.io \"gp2\" not found"], "stdout": "", "stdout_lines": []}
```
**To Reproduce**
Run the Deployer on AWS IPI and 
Specify `storage_type: aws-elastic` in ocp.yaml file

**Expected behavior**
The code should find either gp2-csi or gp3-csi, but it's only finding gp2 which doesn't exist

**Comment by Alan111S** [comment]
Tried running with fixes in fk-misc branch and got further issues:-
`TASK [Get OpenShift storage classes to use for dm and storage class name manta1-elastic] ***
Thursday 16 May 2024  00:51:48 +0000 (0:00:00.364)       0:39:00.769 **********
ERROR! conflicting action statements: set_fact, ocp_storage_class_file

The error appears to be in '/cloud-pak-deployer/automation-roles/40-configure-infra/get-openshift-storage/tasks/main.yml': line 87, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- block:
  - set_fact:
    ^ here

PLAY RECAP *********************************************************************
localhost                  : ok=737  changed=94   unreachable=0    failed=0    skipped=346  rescued=0    ignored=0

Thursday 16 May 2024  00:51:48 +0000 (0:00:00.080)       0:39:00.849 **********
===============================================================================
provision-aws : Run IPI installer for OpenShift cluster manta1, logs are in /root/cpd-status/log/manta1-create-cluster.log  1913.11s
cp4d-variables : Run list-components command --------------------------- 90.94s
openshift-download-installer : Download OpenShift installer "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.14/openshift-install-linux.tar.gz" -- 32.74s
openshift-download-installer : Unpack OpenShift installer -------------- 23.58s
openshift-download-installer : Unpack OpenShift installer -------------- 22.43s
cpd-cli-download : Unpack cpd-cli from /root/cpd-status/downloads/cpd-cli-linux-amd64.tar.gz -- 16.48s
nfs-storage-class : Wait 15 seconds for the dynamic NFS client to deploy -- 15.06s
aws-download-cli : Install aws client ----------------------------------- 7.14s
openshift-download-client : Download OpenShift client "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-4.14/openshift-client-linux.tar.gz" --- 6.64s
openshift-download-client : Unpack OpenShift client from /root/cpd-status/downloads/openshift-client-linux.tar.gz-4.14 --- 6.03s
aws-download-cli : Unpack aws-cli client installer ---------------------- 5.96s
openshift-download-client : Unpack OpenShift client from /root/cpd-status/downloads/openshift-client-linux.tar.gz-4.14 --- 5.64s
aws-download-rosa : Download ROSA client "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz" --- 4.66s
openshift-download-client : Unpack OpenShift client from /root/cpd-status/downloads/openshift-client-linux.tar.gz-4.14 --- 4.32s
cpd-cli-download : Download latest cpd-cli release ---------------------- 4.03s
provision-aws : Create mount target for file server manta1-elastic and subnet subnet-086d525e6d90c34f0 --- 2.66s
openshift-download-installer : Check if OpenShift installer version 4.14 was already downloaded --- 2.59s
provision-aws : Create mount target for file server manta1-elastic and subnet subnet-03b741fc15a4cc454 --- 2.56s
provision-aws : Get existing file systems ------------------------------- 2.55s
provision-aws : Create NFS security group rule if not existent ---------- 2.50s

====================================================================================
Deployer FAILED. Check previous messages. If command line is not returned, press ^C.
[root@manta1-bastion cloud-pak-deployer]#
`

**Comment by fketelaars** [comment]
Fixed, committed in `fk-misc` branch

**Comment by Alan111S** [comment]
Confirm that this issue is resolved
