### ISSUE TITLE
google-flan-t5-xl model missing in cp4d 5.0.0 sample config

### ISSUE THREAD

**Issue by David-M-IBM** [IBM/cloud-pak-deployer#732]
**Describe the bug**
The google-flan-t5-xl model should be added to the [5.0.0 sample config](https://github.com/IBM/cloud-pak-deployer/blob/e1530b3ababdd11b258e9bbdc605bd3dac26ebe8/sample-configurations/sample-dynamic/config-samples/cp4d-500.yaml#L252-L255) as it is one of the three models that can currently be tuned.

The google-flan-t5-xxl is in there currently but that is a different model

**Screenshots**
<img width="1702" alt="image" src="https://github.com/IBM/cloud-pak-deployer/assets/83517881/02ef81ed-85ce-4967-bd0d-69c010ec29c2">

**Comment by fketelaars** [comment]
Done as part of #733
