### ISSUE TITLE
Mirroring filter for Foundation Models

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#753]
When mirroring to a private registry deployer mirrors all watsonx foundation models.  
This results is many hundreds of GBytes of unwanted container images that will not be used.  

There should be a filter option that only mirrors the required foundation models.

The documentation only provides info on excluding watson studio runtimes, not foundation models.
https://www.ibm.com/docs/en/cloud-paks/cp-data/5.0.x?topic=mipcr-mirroring-images-directly-private-container-registry-1

Workaround when manually running the cpd-cli command is to edit
cpd-cli-workspace/work/offline/5.0.0/.ibm-pak/data/cases/9.0.0/ibm-watsonx-ai-ifm-9.0.0+20240528.161801.215-images.csv 
and remove all of the models you don't require, before running the mirror step.

**Comment by fketelaars** [comment]
As from Cloud Pak for Data 5.0.1, it is possible to explicitly mirror specific foundation models using `mirror-images`: https://www.ibm.com/docs/en/cloud-paks/cp-data/5.0.x?topic=mipcr-mirroring-images-directly-private-container-registry-2. However, the command does not provide an option to **exclude** images from being mirrored. Ergo, when not specifying any foundation model, all of them will be mirrored.

The list of images in the `*images.csv` file is built by the `mirror-images` command, hence deployer cannot update the file before the images are mirrored. A potential workaround would be to run a background process that updates the file dynamically, but there's a risk of the file getting corrupted and mirroring failing. Additionally, I have not found a method of identifying the foundation model images and relate them to the models being selected in the deployer config.

Please advise.

**Comment by thomas-mattsson** [comment]
I have added code that adds the specific case groups to filter out the foundation models in PR #786

**Comment by fketelaars** [comment]
Implemented as part of #774
