### ISSUE TITLE
Remove check for downloaded extras

### ISSUE THREAD

**Issue by jandusek4** [IBM/cloud-pak-deployer#772]
**Describe the bug**
If intermittent network issues is hit and download item is downloaded only partially, and its unpacking fails, then subsequent Deployer run fails again as it thinks that the download is already successfully done and only tries to unpack it again.

**To Reproduce**
Not consistent

**Expected behavior**
As an example, remove this check for Java download at https://github.com/IBM/cloud-pak-deployer/blob/main/automation-roles/99-generic/java/java-download/tasks/main.yml#L7-L10

**Screenshots**

**Additional context**

**Comment by fketelaars** [comment]
This issue has also been seen for cpd-cli downloads. Implement the same change for cpd-cli.
