### ISSUE TITLE
Change namespace for NFS from cp-nfs to nfs-provisioner

### ISSUE THREAD

**Issue by Alan111S** [IBM/cloud-pak-deployer#800]
Not exactly a bug but a setting which can cause an issue:-

The namespace name used for NFS is `cp-nfs`

If a CPD administrator later runs `cpd-cli manage setup-nfs-provisioner` commands (e.g. https://www.ibm.com/docs/en/cloud-paks/cp-data/5.0.x?topic=storage-setting-up-dynamic-provisioning), the documentation suggests using the namespace name `nfs-provisioner`.

Quote: "Set PROJECT_NFS_PROVISIONER environment variable to the project (namespace) where you want to deploy the Kubernetes NFS-Client Provisioner provisioner. The recommended project is nfs-provisioner; however, you can specify any project."

Since a deployer user is unlikely to realise that the namespace used by the deployer was different, the act of following that second instruction clobbers the ClusterRoleBinding (run-nfs-client-provisioner) setup by the Deployer.

Then subsequent runs of the Deployer that setup any PVs fail and leave PVCs in 'Pending' state, leading to Deployment failures.

**Comment by Alan111S** [comment]
Simple change in this file `automation-roles/40-configure-infra/nfs-storage-class/vars/main.yml`

Change:-

`nfs_storage_class_project: cp-nfs`

to

`nfs_storage_class_project: nfs-provisioner`

**Comment by fketelaars** [comment]
Making the following changes:
- If no `cp-nfs` project exists, set up the NFS provisioner in namespace `nfs-provisioner`
- If the `cp-nfs` project already exists, set up the NFS provisioner in the `cp-nfs` namespace
