### ISSUE TITLE
cp-deployer fails if cp4d_entitlement is watsonx-gov-risk-compliance 

### ISSUE THREAD

**Issue by elovata** [IBM/cloud-pak-deployer#801]
**Describe the bug**
The cloud-pak-deployer fails if there is in cp4d-50x.yaml file
cp4d_entitlement: watsonx-gov-risk-compliance 

Error in cloud-pak-deployer.log:

fatal: [localhost]: FAILED! => {"attempts": 5, "changed": true, "cmd": "/data/cpdeployer/data/techdemoaigov/status/cp4d/cpd-apply-entitlement.sh\n", "delta": "0:00:00.695723", "end": "2024-10-03 10:08:50.781513", "msg": "non-zero return code", "rc": 1, "start": "2024-10-03 10:08:50.085790", "stderr": "", "stderr_lines": [], "stdout": "[ERROR] 'watsonx-gov-risk-compliance' is not valid for the --entitlement option. You must specify one of the following values:\n\"cognos-analytics\"\n\"cpd-enterprise\"\n\"cpd-standard\"\n\"data-product-hub\"\n\"datastage\"\n\"ikc-premium\"\n\"ikc-standard\"\n\"openpages\"\n\"planning-analytics\"\n\"product-master\"\n\"speech-to-text\"\n\"text-to-speech\"\n\"watson-assistant\"\n\"watson-discovery\"\n\"watsonx-ai\"\n\"watsonx-code-assistant-ansible\"\n\"watsonx-code-assistant-z\"\n\"watsonx-data\"\n\"watsonx-gov-mm\"\n\"watsonx-gov-rc\"\n\"watsonx-orchestrate\"", "stdout_lines": ["[ERROR] 'watsonx-gov-risk-compliance' is not valid for the --entitlement option. You must specify one of the following values:", "\"cognos-analytics\"", "\"cpd-enterprise\"", "\"cpd-standard\"", "\"data-product-hub\"", "\"datastage\"", "\"ikc-premium\"", "\"ikc-standard\"", "\"openpages\"", "\"planning-analytics\"", "\"product-master\"", "\"speech-to-text\"", "\"text-to-speech\"", "\"watson-assistant\"", "\"watson-discovery\"", "\"watsonx-ai\"", "\"watsonx-code-assistant-ansible\"", "\"watsonx-code-assistant-z\"", "\"watsonx-data\"", "\"watsonx-gov-mm\"", "\"watsonx-gov-rc\"", "\"watsonx-orchestrate\""]}

**Comment by fketelaars** [comment]
- [ ] Fix entitlement options
- [ ] Allow for multiple entitlements to be specified
