### ISSUE TITLE
Openshift 4.16 IPI on AWS fails due to incorrect Security Group Names

### ISSUE THREAD

**Issue by Alan111S** [IBM/cloud-pak-deployer#802]
Trying to install OpenShift 4.16 on AWS and this error is being triggered:-
automation-roles/30-provision-infra/provision-aws/tasks/aws-enable-openshift-fileserver.yml line 35
`msg: "Security group with name {{ _current_openshift_cluster.name }}*-worker-sg not found"`

```
<cluster-id>-node
<cluster-id>-lb
<cluster-id>-control-plane
<cluster-id>-apiserver-lb

```

These sg's are attached to the worker nodes:-
```
<cluster-id>-node
<cluster-id>-lb
```
[cloud-pak-deployer.log](https://github.com/user-attachments/files/17264184/cloud-pak-deployer.log)
[cloud-pak-deployer-log-1728016934.tar.gz](https://github.com/user-attachments/files/17264185/cloud-pak-deployer-log-1728016934.tar.gz)
[staging1-delete-cluster.log](https://github.com/user-attachments/files/17264186/staging1-delete-cluster.log)

**Comment by fketelaars** [comment]
@Alan111S you can check the fix in branch `aws-changes`

**Comment by Alan111S** [comment]
@fketelaars There seems to be a problem with this change on AWS. I saw this when creating a 4.14 cluster. Looks like a float vs string comparison issue:-

```
TASK [provision-aws : Set name of compute node security group for OpenShift < 4.16] ***
Tuesday 22 October 2024  07:05:21 +0000 (0:00:00.071)       0:03:18.657 *******
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_current_openshift_cluster.ocp_version < '4.16'' failed. The error was: Unexpected templating type error occurred on ({% if _current_openshift_cluster.ocp_version < '4.16' %} True {% else %} False {% endif %}): '<' not supported between instances of 'float' and 'str'\n\nThe error appears to be in '/cloud-pak-deployer/automation-roles/30-provision-infra/provision-aws/tasks/aws-enable-openshift-fileserver.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set name of compute node security group for OpenShift < 4.16\n  ^ here\n"}

```

**Comment by fketelaars** [comment]
@Alan111S , can you please put the `ocp_version` attribute between single or double quotes?

**Comment by Alan111S** [comment]
@fketelaars Tried putting the `ocp_version` attribute between single or double quotes? Got past the float vs string issue but am back to the original problem:-

```
TASK [provision-aws : Set name of compute node security group for OpenShift < 4.16] ***
Thursday 31 October 2024  04:03:08 +0000 (0:00:00.065)       0:02:27.765 ******

TASK [provision-aws : Set name of compute node security group for OpenShift >= 4.16] ***
Thursday 31 October 2024  04:03:08 +0000 (0:00:00.055)       0:02:27.821 ******

TASK [provision-aws : Get security group for OpenShift cluster compute nodes using filter beta2*-worker-sg] ***
Thursday 31 October 2024  04:03:08 +0000 (0:00:00.043)       0:02:27.864 ******

TASK [provision-aws : debug] ***************************************************
Thursday 31 October 2024  04:03:11 +0000 (0:00:02.545)       0:02:30.410 ******

TASK [provision-aws : Fail if security group was not found] ********************
Thursday 31 October 2024  04:03:11 +0000 (0:00:00.048)       0:02:30.458 ******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Security group with name beta2*-worker-sg not found"}
```

**Comment by Alan111S** [comment]
@fketelaars OK I get what's happening now. To save time I copied some existing vault entries from another cluster
Long story short, that caused the deployer to think the cluster was already built, which was why it was looking for existing security groups

**Comment by fketelaars** [comment]
@Alan111S Did you manage to get past the issue? I will fix the following:

- [ ] Cast the `ocp_version` to `string` so that the check works regardless of how the version was specified
- [ ] Fix the error message, this always states 'worker'

Please let me know if you manage to get past the error.

**Comment by Alan111S** [comment]
Yes I managed to get past the `ocp_version` issue by using quotes.

The second part is more complicated. I think I have confused matters by reusing a vault file from another bastion node. Please let me do some more investigation in the next few hours. I'll update my findings here

**Comment by fketelaars** [comment]
Yes, for some types of installation, the vault is the only method for deployer to determine if the cluster has already been provisioned. Vaults should not be reused for other installations.
