### ISSUE TITLE
IBM Certificate Manager is deprecated -> Replace it by Red Hat Cert Manager

### ISSUE THREAD

**Issue by P-147** [IBM/cloud-pak-deployer#818]
**Is your feature request related to a problem? Please describe.**
At the time of writing, CP4BA is running foundational servie v4.6.5  

I just noticed that IBM Certificate manager (cert-manager) Operator is deprecated since Foundational Service v4.6  ([cf. this link](https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.6?topic=certificate-management#installer-version-4-6-x))  
Foundational Service documentation recommends to [Migrate from IBM Certificate Manager to Red Hat Cert Manager](https://www.ibm.com/docs/en/SSRV9V_4.6/cert-manager/migrating_cert_manager.html).

**Describe the solution you'd like**
Swapping the IBM Certificate manager for the Red Hat one would align with futur usage, and prevent having to do a hotfix the day ibm-cert-manager causes a problem with furtur CloudPak installations.

**Describe alternatives you've considered**
None, as this is the recommended way going forward by the public documentation of IBM Foundational Services.

**Additional context**
N/A

**Comment by fketelaars** [comment]
We will make this change as part of the CP4D 5.1 release #836

**Comment by fketelaars** [comment]
Resolved
