### ISSUE TITLE
Specify different compute_flavour for ocs 

### ISSUE THREAD

**Issue by techietav** [IBM/cloud-pak-deployer#829]
When deploying into IBM ROKS vpc with ocs there is only a single choice for the OpenShift compute_flavour which by default is bx2.16x64 

However this type only has a 100G local disk for ephemeral container images and suffers from 'disk pressure' easily when running lots of pods.  CP4D documentation requires >300G local disk.  
There is an alternate flavour mx2.16x128.2000gb that has a 2TB local disk to avoid this issue for the worker nodes, but if used for OpenShift this also applies to the ocs nodes who could still use the original bx2.16x64 with 100G disk to keep costs down.

There is no way currently to specify the compute_flavour for the ocs node pool

It should be possible to specify a flavour for the ocs node pool, that by default is bx2.16x64

**Comment by techietav** [comment]
Just performed a new install using the compute_flavour mx2.16x128.2000gb and deployer installed the ocs-storage pool using bx2.16x64 which is just the behaviour I wanted!  

Seems the flavour is hard coded for the ocs nodes, so this can be closed.

**Comment by techietav** [comment]
discovered that the deployer is hard coded to use bx2.16x64 as the storage pool which is the desired behaviour.

**Comment by fketelaars** [comment]
I think it would make sense for deployer allowing to choose the server flavour. Will make that change and default to bx2.16x64.
