### ISSUE TITLE
Add EDB Postgress for CP4D.

### ISSUE THREAD

**Issue by fketelaars** [IBM/cloud-pak-deployer#87]
**Is your feature request related to a problem? Please describe.**
Add EDB Postgress cartridge to the deployer for CP4D

**Describe the solution you'd like**
Install according to: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=services-edb-postgres
- [x] Vault secret `edb-postgres-license-key` with EDB Postgres license key must exist
- [x] Create secret with `edb-postgres-license-key` value
- [x] Standard installation with olm-utils or CR

Note: required for customer installation.

**Comment by arthurlaimbock** [comment]
So there currently is a bug in the deployment of cpd-edb, where it attempts to create a CM in the `zen` project, even your CP4D instance is in a different project (e.g. `zen-45`). I am trying to raise this issue (along with some horrible documentation errors) as soon as possible.

The dirty hack to get passed this, is the following:
```
oc new-project zen
oc policy add-role-to-user admin system:serviceaccount:ibm-common-services:ibm-cpd-edb-serviceaccount -n zen
```

Let the operator complete. Then copy the CM ` cpd-edb-aux-br-cm` to the actual project (e.g. zen-45)....

**Comment by fketelaars** [comment]
@arthurlaimbock I have approved and merged the changes. To avoid issues with the EDB installation, can we include the workaround into the deployer code?

**Comment by arthurlaimbock** [comment]
@fketelaars Created issue #90 and support ticket with IBM DEV. I will close this issue, and keep issue #90 until a fix has been made available.
