### ISSUE TITLE
Implement Temporary workaround for CPD EDB 4.5.0 and 4.5.1

### ISSUE THREAD

**Issue by arthurlaimbock** [IBM/cloud-pak-deployer#90]
Due to a hardcoded namespace in the cpd edb operator, the namespace "zen" must be available (with permissions) to allow the CPD EDB operator to create a CM. This CM must then be copied to the actual target CP4D namespace.

A bug report will be created with IBM Development. Once this is fixed, this temporary fix can be removed:
Location of temporary fix:
automation-roles/50-install-cloud-pak/cp4d/cp4d-cartridge-install/tasks/cp4d-prep-cpd-edb.yml

**Comment by arthurlaimbock** [comment]
@fketelaars I have create the case myself: [TS010292533](https://www.ibm.com/mysupport/5003p00002hvkeIAAQ)

**Comment by fketelaars** [comment]
Also fix EnterpriseDB instance provisioning for CP4D 4.7+
