### ISSUE TITLE
Watson Assistant installation failure

### ISSUE THREAD

**Issue by spoisseroux** [IBM/cloud-pak-deployer#92]
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_current_cp4d_cartridge.version < \"4.0.5\"' failed. The error was: error while evaluating conditional (_current_cp4d_cartridge.version < \"4.0.5\"): 'dict object' has no attribute 'version'\n\nThe error appears to be in '/cloud-pak-deployer/automation-roles/50-install-cloud-pak/cp4d/cp4d-cartridge-install/tasks/cp4d-prep-watson-assistant.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n  - name: Run preparation for Watson Assistant\n    ^ here\n"}

**Comment by fketelaars** [comment]
Fixed
